# Estimador de desviación estándar *leave-one-out (LOO)* 

Considere un conjunto de datos $(x_{1i}, \ldots, x_{6i})$ y $y_i$, donde $i = 1, \ldots, n$. A partir de este conjunto, es posible estimar el modelo de regresión lineal:

$$ y_i = \beta_0 + \beta_1 x_{1i} + \beta_2 x_{2i} + \beta_3 x_{3i}+ \beta_4 x_{4i}+ \beta_5 x_{5i}+ \beta_6 x_{6i}$$ 

el cual puede expresarse en forma matricial como $y = X\beta$, donde $\beta$ corresponde al vector de parámetros del modelo.


In [47]:
import numpy as np
import statsmodels.formula.api as sm
import pandas as pd

In [60]:
n = 50

In [61]:
x3 = np.random.randint(0, 20, (n, 3))

In [62]:
x4 = 10*np.random.random((n, 3))

In [63]:
X = np.column_stack((np.ones(n), x3, x4))
X.shape

(50, 7)

In [64]:
beta = np.array([1., 0.3, 0.5, 0.7, 2.1, 1.5, 1.8]).reshape((7, 1))
beta

array([[1. ],
       [0.3],
       [0.5],
       [0.7],
       [2.1],
       [1.5],
       [1.8]])

In [65]:
y = np.matmul(X, beta) + 5*(np.random.random((n, 1)) - 1)
y

array([[34.82125672],
       [44.80589205],
       [31.08735857],
       [37.99315444],
       [21.41242039],
       [47.3197688 ],
       [26.7119935 ],
       [32.95108779],
       [47.69022077],
       [35.34568792],
       [45.11883709],
       [40.07752994],
       [22.12878336],
       [37.33331689],
       [40.72323415],
       [43.22083647],
       [29.71760437],
       [39.79408285],
       [45.29352448],
       [14.33655517],
       [33.4533468 ],
       [44.46526101],
       [18.44277459],
       [30.5968086 ],
       [41.19098272],
       [34.20199091],
       [30.63295535],
       [29.99844424],
       [45.96918599],
       [28.75448255],
       [38.9279507 ],
       [32.10801135],
       [13.39371941],
       [39.63161144],
       [57.12383568],
       [45.04025704],
       [30.47677385],
       [17.44466137],
       [44.69783568],
       [42.23580397],
       [21.57174446],
       [39.13058875],
       [36.78494408],
       [42.99411474],
       [48.99101108],
       [23

In [66]:
data = np.column_stack((X, y))
data

array([[1.00000000e+00, 1.60000000e+01, 1.00000000e+00, 3.00000000e+00,
        5.71817495e+00, 5.74296768e+00, 3.62430396e+00, 3.48212567e+01],
       [1.00000000e+00, 5.00000000e+00, 1.90000000e+01, 0.00000000e+00,
        7.21603202e+00, 3.05135780e+00, 9.01730965e+00, 4.48058921e+01],
       [1.00000000e+00, 1.10000000e+01, 3.00000000e+00, 5.00000000e+00,
        5.35482202e+00, 5.25215933e-01, 8.02328755e+00, 3.10873586e+01],
       [1.00000000e+00, 1.90000000e+01, 1.80000000e+01, 0.00000000e+00,
        1.50374100e+00, 3.07021641e+00, 9.53886385e+00, 3.79931544e+01],
       [1.00000000e+00, 1.90000000e+01, 1.30000000e+01, 0.00000000e+00,
        2.81754392e+00, 3.08919454e+00, 4.85237186e-01, 2.14124204e+01],
       [1.00000000e+00, 3.00000000e+00, 0.00000000e+00, 1.10000000e+01,
        6.93762736e+00, 8.65858590e+00, 8.20375946e+00, 4.73197688e+01],
       [1.00000000e+00, 1.30000000e+01, 1.90000000e+01, 3.00000000e+00,
        1.52413420e+00, 6.58181466e-01, 4.70675807e+00, 2.

In [67]:
np.savetxt('data.txt', data)
np.savetxt('data.csv', data, delimiter=',')
np.save('data', data)

In [68]:
df = pd.DataFrame(data, columns=['1s','x1','x2','x3','x4','x5','x6','y'])
df = df.iloc[:, 1:]
df

x1    x2    x3        x4        x5        x6          y
0   16.0   1.0   3.0  5.718175  5.742968  3.624304  34.821257
1    5.0  19.0   0.0  7.216032  3.051358  9.017310  44.805892
2   11.0   3.0   5.0  5.354822  0.525216  8.023288  31.087359
3   19.0  18.0   0.0  1.503741  3.070216  9.538864  37.993154
4   19.0  13.0   0.0  2.817544  3.089195  0.485237  21.412420
5    3.0   0.0  11.0  6.937627  8.658586  8.203759  47.319769
6   13.0  19.0   3.0  1.524134  0.658181  4.706758  26.711993
7   13.0   0.0   0.0  9.663613  3.302648  2.049603  32.951088
8    2.0   8.0  15.0  8.862070  0.699296  9.240629  47.690221
9    4.0  12.0  11.0  9.520994  1.558143  0.291961  35.345688
10   3.0   2.0  11.0  7.947461  4.842449  8.151155  45.118837
11  17.0   7.0  11.0  5.523718  3.045762  5.155733  40.077530
12  10.0   7.0   5.0  4.933251  0.092834  1.141773  22.128783
13   8.0   2.0  13.0  2.155308  7.994517  6.528307  37.333317
14   3.0   0.0  18.0  3.223047  5.467985  6.630295  40.723234
15  14.0  12.0   4.0  9.332987  5.473666  1.241593  43.220836
16  13.0  13.0  16.0  2.625960  0.920071  1.560500  29.717604
17   1.0  19.0   9.0  5.837082  1.226263  6.635912  39.794083
18  17.0  10.0   7.0  3.489025  6.997158  8.644662  45.293524
19  14.0   7.0   0.0  0.062790  0.294461  4.791616  14.336555
20  15.0   3.0   6.0  5.175799  6.658746  2.654502  33.453347
21  11.0   6.0   1.0  9.467693  5.104885  6.549674  44.465261
22   3.0   0.0   4.0  3.582711  6.290217  0.577732  18.442775
23  16.0   5.0   3.0  0.651578  7.889200  4.912863  30.596809
24   1.0   2.0   8.0  7.921105  8.896315  2.674785  41.190983
25   2.0   0.0   4.0  6.303839  0.024409  9.570537  34.201991
26   3.0  17.0   5.0  4.068294  4.729967  1.623407  30.632955
27  18.0   5.0  13.0  3.731259  2.048565  3.029863  29.998444
28   6.0  16.0   1.0  7.747873  1.578920  9.310106  45.969186
29   1.0   2.0  11.0  3.996033  0.741192  5.655334  28.754483
30   2.0   3.0   0.0  9.113652  1.120706  9.087749  38.927951
31  11.0  15.0   3.0  5.624441  1.566043  4.700300  32.108011
32  16.0   0.0   1.0  2.081597  0.550870  3.268920  13.393719
33   5.0   0.0  11.0  7.573729  4.168661  5.423416  39.631611
34   7.0  16.0  19.0  8.234612  3.672349  8.143774  57.123836
35  11.0   3.0  16.0  1.911732  6.941344  7.875192  45.040257
36   7.0  10.0  14.0  4.088087  4.023513  0.500605  30.476774
37   9.0  10.0   1.0  0.350787  1.114894  4.554608  17.444661
38   0.0   3.0  18.0  1.773855  7.694683  9.242379  44.697836
39   6.0   9.0  14.0  8.525702  2.492404  4.309911  42.235804
40  14.0  15.0   9.0  0.009810  0.234581  1.498062  21.571744
41  13.0   7.0   4.0  7.440584  2.130331  6.239203  39.130589
42  14.0   4.0  19.0  3.745340  4.036158  3.501069  36.784944
43   3.0  16.0  19.0  2.662802  7.466088  1.713550  42.994115
44  14.0   2.0  14.0  8.641113  2.468610  6.667793  48.991011
45   3.0  13.0   5.0  2.197255  3.175513  3.024222  23.195772
46  17.0   4.0  10.0  5.341209  6.616901  6.512719  47.640444
47   5.0  13.0   1.0  7.550595  7.295056  8.866268  49.212016
48   2.0   4.0  12.0  0.354668  2.455803  2.494228  18.994648
49   8.0  16.0  19.0  6.711509  4.078057  8.378116  55.136326

In [69]:
result = sm.ols(formula='y ~ x1 + x2 + x3 + x4 + x5 + x6', data=df).fit()
print(result.summary())

                            OLS Regression Results                            
Dep. Variable:                      y   R-squared:                       0.982
Model:                            OLS   Adj. R-squared:                  0.979
Method:                 Least Squares   F-statistic:                     390.5
Date:                Thu, 16 Jan 2020   Prob (F-statistic):           8.07e-36
Time:                        18:02:13   Log-Likelihood:                -87.836
No. Observations:                  50   AIC:                             189.7
Df Residuals:                      43   BIC:                             203.1
Df Model:                           6                                         
Covariance Type:            nonrobust                                         
                 coef    std err          t      P>|t|      [0.025      0.975]
------------------------------------------------------------------------------
Intercept     -0.6917      0.943     -0.733      0.4

In [70]:
result.params

Intercept   -0.691715
x1           0.285130
x2           0.473372
x3           0.671312
x4           2.074063
x5           1.527403
x6           1.733444
dtype: float64

In [71]:
beta

array([[1. ],
       [0.3],
       [0.5],
       [0.7],
       [2.1],
       [1.5],
       [1.8]])