# Introducción a las ciencias de la computación *y programación en Python*


## *Numerical Python*: NumPy

<img src="logo-banguat.png" alt="Banco de Guatemala" style="width: 100px;"/>

### Rodrigo Chang
#### Banco de Guatemala

## Abstract

> ### "*I do not fear computers. I fear lack of them.*" **Isaac Asimov**

- Paquete de computación científica NumPy

    - Introducción
    
    - Conceptos básicos de utilización
    
    - Ejercicios

# NumPy

- Paquete de Python para **computación científica** de **alto desempeño** sobre vectores, matrices y estructuras de mayores dimensiones (tensores).

- Implementado en C y Fortran, por lo que cuando se **vectorizan** las oepraciones, el desempeño es muy bueno.

- Ofrece una estructura de datos `ndarray` para procesar de forma **eficiente** datos homogéneos.

- Capacidades de algebra lineal, transformada de Fourier y generación de números aleatorios.

# Pero, ¿y las listas de Python?

- Las listas son muy generales, pueden contener cualquier tipo de objeto.

    - Implementan tipos dinámicos.
    
    - No permiten operaciones matemáticas como la *multiplicación matricial* o *producto punto*.
    
- Los vectores de NumPy son de tipado estático y homogéneo. El tipo del arreglo se determina cuando se crea el vector.

    - Son eficientes en memoria.
    
    - Es posible implementar **funciones universales** (ufuncs). 
    
    - El tipado estático permite implementar operaciones matemáticas de forma eficiente a través de C y Fortran.
    

### Scientific computing benchmark



[5 Reasons You Should Know NumPy](https://insights.dice.com/2016/09/01/5-reasons-know-numpy/)

## Importando NumPy

In [2]:
import numpy as np

- Revisamos la versión de NumPy

In [2]:
np.__version__

'1.16.5'

### Obteniendo ayuda

In [3]:
# Obtiene una ventana de ayuda
np.ndarray?

In [4]:
# Función help para una función
help(np.array)

Help on built-in function array in module numpy:

array(...)
    array(object, dtype=None, copy=True, order='K', subok=False, ndmin=0)
    
    Create an array.
    
    Parameters
    ----------
    object : array_like
        An array, any object exposing the array interface, an object whose
        __array__ method returns an array, or any (nested) sequence.
    dtype : data-type, optional
        The desired data-type for the array.  If not given, then the type will
        be determined as the minimum type required to hold the objects in the
        sequence.  This argument can only be used to 'upcast' the array.  For
        downcasting, use the .astype(t) method.
    copy : bool, optional
        If true (default), then the object is copied.  Otherwise, a copy will
        only be made if __array__ returns a copy, if obj is a nested sequence,
        or if a copy is needed to satisfy any of the other requirements
        (`dtype`, `order`, etc.).
    order : {'K', 'A', 'C', 'F'}

***
## La clase `ndarray`

- La clase básica de NumPy se llama `ndarray` (alias `array`). Sus atributos más importantes son: 

    - `ndarray.ndim` : número de dimensiones del arreglo.

    - `ndarray.shape` : dimensiones del arreglo. Esta es una **tupla de enteros** que indica el tamaño de la matriz en cada dimensión. Para una matriz con $n$ filas y $m$ columnas, la forma será $(n, m)$. La longitud de la tupla de forma es, por lo tanto, el número de ejes, `ndim`.

    - `darray.size` : el número total de elementos del arreglo. Es igual al producto de los elementos de la tupla `shape`.

    - `ndarray.dtype` : un **objeto** que describe el **tipo** de los elementos en el arreglo. Es posible crear y especificar `dtypes` propios.
        - Adicionalmente, NumPy provee algunos tipos propios muy utilizados: `numpy.int32`, `numpy.int16`, and `numpy.float64`.

    - `ndarray.itemsize` : el tamaño en bytes de cada elemento en el arreglo. Por ejemplo, un arreglo de tipo `float64` tiene tamaño en bytes de $8 (=64/8)$. Equivalente a `ndarray.dtype.itemsize`.

    - `ndarray.data` : el búfer que contiene los elementos del arreglo. Aunque normalmente, no accedemos al atributo directamente, ya que hacemos uso de los elementos con *slicing*.



In [6]:
a = np.arange(15).reshape(3, 5)
a

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [10]:
len(a.shape)

2

In [11]:
a.ndim

2

In [13]:
type(a.dtype)

numpy.dtype

In [14]:
a.dtype.name

'int32'

In [15]:
a.itemsize

4

In [16]:
a.size

15

In [17]:
type(a)

numpy.ndarray

***
## **Creando arreglos N-dimensionales de NumPy**

- Hay varias formas de inicializar nuevas matrices numpy, por ejemplo desde

    - Una lista de Python o tuplas.
    
    - Utilizando funciones dedicadas a **generar** arreglos de NumPy.
    
    - Leer información de archivos. 

In [20]:
a = np.array([2.,3,4])
a

array([2., 3., 4.])

In [21]:
a.dtype

dtype('float64')

In [22]:
a.astype(np.int32)

array([2, 3, 4])

In [28]:
b = np.array([1.2, 3.9, 5.1])
b

array([1.2, 3.9, 5.1])

In [29]:
b.astype(np.int32)

array([1, 3, 5])

In [22]:
b.dtype

dtype('float64')

#### Error frecuente

Crear el arreglo con varios argumentos en vez de proveer una sola lista o secuencia como argumento

In [32]:
# Error frecuente
a = np.array([1,2,3,4])

### A partir de listas o tuplas 
`ndarray` transforma secuencias de secuencias en matrices bidimensionales, secuencias de secuencias de secuencias en matrices tridimensionales, etc.

In [33]:
b = np.array([[1.5,2,3], [4,5,6]])
b

array([[1.5, 2. , 3. ],
       [4. , 5. , 6. ]])

El tipo de matriz también se puede especificar explícitamente en el momento de la creación:

In [35]:
c = np.array( [ [1,2], [3,4] ], dtype=np.bool )
c

array([[ True,  True],
       [ True,  True]])

### Funciones de generación de arreglos

In [36]:
np.arange(10, 30, 5)

array([10, 15, 20, 25])

In [37]:
# A diferencia de range
np.arange(0, 2, 0.3)

array([0. , 0.3, 0.6, 0.9, 1.2, 1.5, 1.8])

In [47]:
x,dx=np.linspace(0,100,15,retstep=True)
print(x)

[  0.           7.14285714  14.28571429  21.42857143  28.57142857
  35.71428571  42.85714286  50.          57.14285714  64.28571429
  71.42857143  78.57142857  85.71428571  92.85714286 100.        ]


#### Evaluación de funciones

In [48]:
x = np.linspace(0, 2*np.pi, 20)
x

array([0.        , 0.33069396, 0.66138793, 0.99208189, 1.32277585,
       1.65346982, 1.98416378, 2.31485774, 2.64555171, 2.97624567,
       3.30693964, 3.6376336 , 3.96832756, 4.29902153, 4.62971549,
       4.96040945, 5.29110342, 5.62179738, 5.95249134, 6.28318531])

In [52]:
import math
math.sin([3.1416,2.25])



TypeError: must be real number, not list

In [53]:
y = np.sin([3.1416,2.2568])
y 

array([-7.34641021e-06,  7.73783660e-01])

####  Variables aleatorias

In [55]:
b = np.random.random((5000, 5000))
b

array([[0.1545585 , 0.40424743, 0.51573147, ..., 0.0960105 , 0.96904842,
        0.87306277],
       [0.9349992 , 0.35559499, 0.42547308, ..., 0.79135404, 0.98062466,
        0.75574363],
       [0.25982303, 0.95144953, 0.67029977, ..., 0.57779471, 0.47549523,
        0.07177726],
       ...,
       [0.81784323, 0.38034092, 0.24021679, ..., 0.32491688, 0.29544898,
        0.79781852],
       [0.45161471, 0.85486029, 0.94014881, ..., 0.25431049, 0.85650561,
        0.79835524],
       [0.72412084, 0.85523799, 0.35511128, ..., 0.30707146, 0.80373575,
        0.57242791]])

#### Unos, ceros

In [41]:
np.zeros([10, 10])

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]])

In [42]:
np.ones([5, 5])

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [58]:
print(x.shape)
x=np.random.random((5,4,3,2,1))
x

(20,)


array([[[[[0.42594709],
          [0.05861935]],

         [[0.52711438],
          [0.07315357]],

         [[0.81821177],
          [0.6759236 ]]],


        [[[0.47090452],
          [0.72257236]],

         [[0.17769006],
          [0.76779062]],

         [[0.11665137],
          [0.67981311]]],


        [[[0.72782545],
          [0.81157432]],

         [[0.3858371 ],
          [0.03988629]],

         [[0.09588232],
          [0.38458754]]],


        [[[0.46428928],
          [0.42455059]],

         [[0.62967606],
          [0.61190525]],

         [[0.11428923],
          [0.91190378]]]],



       [[[[0.42808335],
          [0.78365618]],

         [[0.86513747],
          [0.64399761]],

         [[0.88244413],
          [0.7316503 ]]],


        [[[0.94799572],
          [0.06228485]],

         [[0.83983818],
          [0.42211874]],

         [[0.52878299],
          [0.78973131]]],


        [[[0.26041747],
          [0.48211385]],

         [[0.54752654],
          [0

In [59]:
# Copiando la forma de x
np.ones_like(x)


array([[[[[1.],
          [1.]],

         [[1.],
          [1.]],

         [[1.],
          [1.]]],


        [[[1.],
          [1.]],

         [[1.],
          [1.]],

         [[1.],
          [1.]]],


        [[[1.],
          [1.]],

         [[1.],
          [1.]],

         [[1.],
          [1.]]],


        [[[1.],
          [1.]],

         [[1.],
          [1.]],

         [[1.],
          [1.]]]],



       [[[[1.],
          [1.]],

         [[1.],
          [1.]],

         [[1.],
          [1.]]],


        [[[1.],
          [1.]],

         [[1.],
          [1.]],

         [[1.],
          [1.]]],


        [[[1.],
          [1.]],

         [[1.],
          [1.]],

         [[1.],
          [1.]]],


        [[[1.],
          [1.]],

         [[1.],
          [1.]],

         [[1.],
          [1.]]]],



       [[[[1.],
          [1.]],

         [[1.],
          [1.]],

         [[1.],
          [1.]]],


        [[[1.],
          [1.]],

         [[1.],
          

In [62]:
np.identity(100)

array([[1., 0., 0., ..., 0., 0., 0.],
       [0., 1., 0., ..., 0., 0., 0.],
       [0., 0., 1., ..., 0., 0., 0.],
       ...,
       [0., 0., 0., ..., 1., 0., 0.],
       [0., 0., 0., ..., 0., 1., 0.],
       [0., 0., 0., ..., 0., 0., 1.]])

### Desde archivos

In [63]:
data = np.loadtxt("data.csv", delimiter=',', skiprows=1)
data

array([[1.00000000e+00, 3.44899870e-01],
       [2.00000000e+00, 9.31072695e-01],
       [3.00000000e+00, 6.25704035e-01],
       [4.00000000e+00, 8.41599361e-01],
       [5.00000000e+00, 8.87112967e-01],
       [6.00000000e+00, 5.58222238e-01],
       [7.00000000e+00, 3.05687170e-02],
       [8.00000000e+00, 7.21006651e-01],
       [9.00000000e+00, 2.15081930e-02],
       [1.00000000e+01, 4.89341526e-01],
       [1.10000000e+01, 3.23284084e-01],
       [1.20000000e+01, 1.86885658e-01],
       [1.30000000e+01, 4.64906445e-01],
       [1.40000000e+01, 5.60553301e-01],
       [1.50000000e+01, 3.83349378e-01],
       [1.60000000e+01, 4.76682101e-01],
       [1.70000000e+01, 9.40387708e-01],
       [1.80000000e+01, 4.03836182e-01],
       [1.90000000e+01, 8.30264821e-01],
       [2.00000000e+01, 2.50129241e-01],
       [2.10000000e+01, 5.85427477e-01],
       [2.20000000e+01, 9.33801603e-01],
       [2.30000000e+01, 6.32389807e-01],
       [2.40000000e+01, 1.85051348e-01],
       [2.500000

***
## Impresión de arreglos

Cuando imprimes una matriz, NumPy la muestra de forma similar a las listas anidadas, pero con el siguiente diseño:

- el último eje se imprime de izquierda a derecha,

- el penúltimo se imprime de arriba a abajo,

- el resto también se imprime de arriba a abajo, con cada corte separado del siguiente por una línea vacía.

Las matrices unidimensionales se imprimen como filas, bidimensionales como matrices y tridimensionales como listas de matrices.

In [64]:
a = np.arange(6)
print(a)

[0 1 2 3 4 5]


In [65]:
b = np.arange(12).reshape(4,3)
print(b)

[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]]


In [67]:
c = np.arange(48).reshape(2,2,3,4) 
print(c)

[[[[ 0  1  2  3]
   [ 4  5  6  7]
   [ 8  9 10 11]]

  [[12 13 14 15]
   [16 17 18 19]
   [20 21 22 23]]]


 [[[24 25 26 27]
   [28 29 30 31]
   [32 33 34 35]]

  [[36 37 38 39]
   [40 41 42 43]
   [44 45 46 47]]]]


In [68]:
# Si es muy grande, se suprime parte de la salida
print(np.arange(10000))

[   0    1    2 ... 9997 9998 9999]


In [69]:
print(np.arange(10000).reshape(100,100))

[[   0    1    2 ...   97   98   99]
 [ 100  101  102 ...  197  198  199]
 [ 200  201  202 ...  297  298  299]
 ...
 [9700 9701 9702 ... 9797 9798 9799]
 [9800 9801 9802 ... 9897 9898 9899]
 [9900 9901 9902 ... 9997 9998 9999]]


***
## Operaciones básicas

Las operaciones básicas son aplicadas elemento a elemento (*elementwise*). Se crea un nuevo arreglo lleno con el resultado

In [70]:
a = np.array( [20,30,40,50] )
b = np.arange(4)
a, b

(array([20, 30, 40, 50]), array([0, 1, 2, 3]))

In [71]:
c = a - b
c

array([20, 29, 38, 47])

`*` opera en sentido elemento a elemento sobre los arreglos.

In [72]:
# Constante por arreglo
10 * np.sin(a)

array([ 9.12945251, -9.88031624,  7.4511316 , -2.62374854])

In [74]:
# Arreglos lógicos
a < 35

array([ True,  True, False, False])

La multiplicación matricial puede hacerse utilizando `@` o el método `dot`

In [75]:
A = np.array( [[1, 1], [0, 1]] )
B = np.array( [[2, 0], [3, 4]] )

In [76]:
A * B

array([[2, 0],
       [0, 4]])

In [77]:
A @ B

array([[5, 4],
       [3, 4]])

In [78]:
A.dot(B)

array([[5, 4],
       [3, 4]])

In [79]:
np.matmul(A, B)

array([[5, 4],
       [3, 4]])

In [74]:
b = np.random.random((2,3))
b

array([[0.09859514, 0.2208616 , 0.5853165 ],
       [0.38964511, 0.29757204, 0.12178976]])

Operadores `+=` y `*=` son válidos para modificar arreglos existentes.

In [80]:
a = np.ones((2,3), dtype=int)
a *= 3
a

array([[3, 3, 3],
       [3, 3, 3]])

In [81]:
b = np.random.random((2,3))
b +=a 
b

array([[3.31434878, 3.3501838 , 3.88228058],
       [3.37244375, 3.11341827, 3.01125427]])

### Métodos útiles

In [82]:
a = np.random.random((2, 3))
a

array([[0.1166214 , 0.9253785 , 0.80680835],
       [0.05689657, 0.57325232, 0.04503846]])

In [83]:
a.sum() # equivalente a np.sum(a)

2.523995607858355

In [84]:
a.min()

0.04503846128788824

In [85]:
a.max()

0.9253785038007231

Por defecto operan sobre el arreglo como si fueran una lista de números. Es posible especificar el eje sobre el cuál se desea aplicar la operación con el parámetro `axis`

In [13]:
b = np.arange(12).reshape(3,4)
b

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [12]:
# Mínimo de cada fila
b.min(axis=1)

array([0, 4, 8])

In [14]:
# Suma acumulada en las columnas 
b.cumsum(axis=1)

array([[ 0,  1,  3,  6],
       [ 4,  9, 15, 22],
       [ 8, 17, 27, 38]], dtype=int32)

***
## Funciones universales (*ufuncs*)

In [20]:
a = np.random.random((10,10))
a

array([[5.58614354e-01, 7.20942598e-01, 7.21570615e-01, 2.23027197e-01,
        5.37447680e-02, 1.79358568e-01, 2.19578001e-01, 1.87422220e-01,
        4.77708886e-01, 3.11489969e-01],
       [2.34297769e-02, 9.30206344e-01, 9.79743334e-01, 7.40569029e-01,
        6.62773793e-01, 2.27302673e-01, 6.64778664e-01, 1.94350704e-01,
        6.30748813e-01, 1.34697235e-01],
       [8.46446801e-02, 2.22712101e-01, 2.39722034e-01, 6.86407666e-01,
        3.28109821e-01, 4.63139141e-01, 6.29972478e-02, 3.36245246e-01,
        7.25894287e-01, 4.99665394e-01],
       [4.50490012e-01, 1.83801890e-01, 5.31342077e-01, 4.70506201e-01,
        3.38266483e-01, 5.57160544e-01, 7.09492659e-01, 8.19459814e-01,
        2.49007878e-01, 4.81112437e-01],
       [5.93150715e-01, 4.37870763e-01, 7.02376298e-01, 2.64681371e-02,
        9.23889613e-01, 4.77220932e-01, 8.21302223e-01, 8.09388468e-01,
        1.26606970e-01, 5.72337546e-01],
       [5.16056540e-01, 8.11494921e-02, 6.06475452e-02, 1.75379883e-01,
   

In [16]:
np.exp(a)

array([ 1.        ,  2.71828183,  7.3890561 , 20.08553692, 54.59815003])

In [17]:
np.sqrt(a)

array([0.        , 1.        , 1.41421356, 1.73205081, 2.        ])

Podemos definir funciones de usuario que sean universales: $$ f(x) = 2x + e^x - \sqrt{x} $$

In [21]:
def f(x):
    return 2*x + np.exp(x) - np.sqrt(x)

In [22]:
f(a)

array([[2.118072  , 2.64917244, 2.65135057, 1.22365141, 0.9308756 ,
        1.13165935, 1.21611549, 1.14805799, 1.87662893, 1.43032516],
       [0.91749808, 3.43097284, 3.63343927, 2.71770336, 2.45160488,
        1.23305237, 2.45827791, 1.16237131, 2.34631775, 1.04657356],
       [0.96668206, 1.22296118, 1.26072573, 2.53088439, 1.47175236,
        1.83478944, 0.94002588, 1.49230617, 2.66637266, 1.94063034],
       [1.79887536, 1.14066027, 2.03496594, 1.85588217, 1.49744035,
        2.11359781, 2.60963104, 3.00295311, 1.281761  , 1.88647537],
       [2.22581988, 1.76342814, 2.58521734, 0.91706749, 3.40565702,
        1.87521953, 3.00980565, 2.96565048, 1.03236606, 2.16055045],
       [1.98915003, 0.9619645 , 0.93755222, 1.12367479, 1.11774365,
        3.56906542, 1.92220392, 1.05762795, 3.24147881, 1.01237602],
       [0.91828309, 1.84681122, 2.87193784, 2.48655208, 1.64690318,
        1.35140727, 3.0766545 , 2.9884107 , 0.91704934, 2.71146684],
       [2.06533864, 1.4244248 , 1.6218913

***
## Indexing, Slicing and Iterating

Los arreglos unidimensionales se pueden indexar, dividir e iterar, al igual que las listas y otras secuencias de Python.

In [23]:
a = np.arange(10)**3
a

array([  0,   1,   8,  27,  64, 125, 216, 343, 512, 729], dtype=int32)

In [24]:
a[2]

8

In [25]:
a[2:5]

array([ 8, 27, 64], dtype=int32)

In [26]:
a[0:6:2]

array([ 0,  8, 64], dtype=int32)

In [27]:
# Asignación múltiple
a[0:6:2] = -1000
a

array([-1000,     1, -1000,    27, -1000,   125,   216,   343,   512,
         729], dtype=int32)

In [28]:
for i in a:
    print(i**(1/3.))

nan
1.0
nan
3.0
nan
5.0
5.999999999999999
6.999999999999999
7.999999999999999
8.999999999999998


C:\ProgramData\Anaconda3\lib\site-packages\ipykernel_launcher.py:2: RuntimeWarning: invalid value encountered in power
  


In [29]:
def f(x,y):
    return 10*x + y

In [30]:
b = np.fromfunction(f, (5,4), dtype=int)
b

array([[ 0,  1,  2,  3],
       [10, 11, 12, 13],
       [20, 21, 22, 23],
       [30, 31, 32, 33],
       [40, 41, 42, 43]])

In [31]:
b[2, 3]

23

In [130]:
#Ojo con la dimensión de b
b[0:5, 1]

array([ 1, 11, 21, 31, 41])

In [39]:
b[:, 0::2]

array([[ 0,  2],
       [10, 12],
       [20, 22],
       [30, 32],
       [40, 42]])

Cuando se proporcionan menos índices que el número de ejes, los índices faltantes se consideran segmentos completos `:`

In [41]:
# Ultima fila, todas las columnas
b[-1,:]

array([40, 41, 42, 43])

In [137]:
np.ones((5,4,3,2,1))

array([[[[[1.],
          [1.]],

         [[1.],
          [1.]],

         [[1.],
          [1.]]],


        [[[1.],
          [1.]],

         [[1.],
          [1.]],

         [[1.],
          [1.]]],


        [[[1.],
          [1.]],

         [[1.],
          [1.]],

         [[1.],
          [1.]]],


        [[[1.],
          [1.]],

         [[1.],
          [1.]],

         [[1.],
          [1.]]]],



       [[[[1.],
          [1.]],

         [[1.],
          [1.]],

         [[1.],
          [1.]]],


        [[[1.],
          [1.]],

         [[1.],
          [1.]],

         [[1.],
          [1.]]],


        [[[1.],
          [1.]],

         [[1.],
          [1.]],

         [[1.],
          [1.]]],


        [[[1.],
          [1.]],

         [[1.],
          [1.]],

         [[1.],
          [1.]]]],



       [[[[1.],
          [1.]],

         [[1.],
          [1.]],

         [[1.],
          [1.]]],


        [[[1.],
          [1.]],

         [[1.],
          

La iteración sobre matrices multidimensionales se realiza con respecto al primer eje

In [42]:
for row in b:
    print(row)

[0 1 2 3]
[10 11 12 13]
[20 21 22 23]
[30 31 32 33]
[40 41 42 43]


Sin embargo, si se desea realizar una operación en cada elemento de la matriz, se puede usar el atributo `flat` que es un iterador sobre todos los elementos de la matriz:

In [43]:
for element in b.flat:
    print(element)

0
1
2
3
10
11
12
13
20
21
22
23
30
31
32
33
40
41
42
43


In [44]:
b.flatten()

array([ 0,  1,  2,  3, 10, 11, 12, 13, 20, 21, 22, 23, 30, 31, 32, 33, 40,
       41, 42, 43])

***
## Manipulación del `shape` (forma) del arreglo

Una matriz tiene una forma dada por el número de elementos a lo largo de cada eje:

In [3]:
a = np.floor ( 10 * np.random.random (( 3 , 4 )))
a

array([[5., 9., 9., 7.],
       [6., 1., 7., 8.],
       [2., 5., 9., 8.]])

In [1]:
import numpy as np

In [4]:
a.shape

(3, 4)

La forma de una matriz se puede cambiar con varios comandos. Tenga en cuenta que los siguientes tres comandos devuelven una matriz modificada, pero **no cambian la matriz original**:

In [5]:
a.ravel()  # returns the array, flattened

array([5., 9., 9., 7., 6., 1., 7., 8., 2., 5., 9., 8.])

In [6]:
a.flatten()

array([5., 9., 9., 7., 6., 1., 7., 8., 2., 5., 9., 8.])

In [7]:
a.reshape(6,2)  # returns the array with a modified shape

array([[5., 9.],
       [9., 7.],
       [6., 1.],
       [7., 8.],
       [2., 5.],
       [9., 8.]])

In [9]:
a

array([[5., 9., 9., 7.],
       [6., 1., 7., 8.],
       [2., 5., 9., 8.]])

In [8]:
a.T

array([[5., 6., 2.],
       [9., 1., 5.],
       [9., 7., 9.],
       [7., 8., 8.]])

In [10]:
a.T.shape

(4, 3)

- El orden de los elementos en la matriz resultante de `ravel()` es normalmente "estilo `C`", es decir, el índice de la derecha "cambia más rápido", por lo que el elemento después de un `[0,0]` es un `[0,1]`. 

- Si la matriz se reforma a otra forma, nuevamente la matriz se trata como "estilo `C`". NumPy normalmente crea matrices almacenadas en este orden, por lo que `ravel()` generalmente no necesitará copiar su argumento, pero si la matriz se hizo tomando segmentos de otra matriz o se creó con opciones inusuales, es posible que deba copiarse. 

- Las funciones `ravel()` y `reshape()` también se pueden instruir, utilizando un argumento opcional, para usar matrices de estilo FORTRAN, en las que el índice más a la izquierda cambia más rápido.

La función de `reshape` devuelve su argumento con una forma modificada, mientras que el método `ndarray.resize` modifica la matriz en sí:

In [11]:
a

array([[5., 9., 9., 7.],
       [6., 1., 7., 8.],
       [2., 5., 9., 8.]])

In [13]:
a.resize((2, 6))
a

array([[5., 9., 9., 7., 6., 1.],
       [7., 8., 2., 5., 9., 8.]])

In [14]:
a

array([[5., 9., 9., 7., 6., 1.],
       [7., 8., 2., 5., 9., 8.]])

***
## Apilando los arreglos 
Se pueden apilar varios arreglos a lo largo de diferentes ejes:

In [158]:
a = np.floor(10*np.random.random((2,2)))
a

array([[0., 1.],
       [3., 7.]])

In [160]:
b = np.floor(10*np.random.random((2,2)))
b

array([[2., 2.],
       [6., 7.]])

In [161]:
# np.vstack pide una tupla de ndarrays 
np.vstack((a,b))

array([[0., 1.],
       [3., 7.],
       [2., 2.],
       [6., 7.]])

In [163]:
# np.hstack pide una tupla de ndarrays 
np.hstack((a,b))

array([[0., 1., 2., 2.],
       [3., 7., 6., 7.]])

In [165]:
np.column_stack((a,b)) # Equivalente a np.hstack para arreglos 2D

array([[0., 1., 2., 2.],
       [3., 7., 6., 7.]])

In [166]:
np.hstack((a,b)) 

array([[0., 1., 2., 2.],
       [3., 7., 6., 7.]])

- Cuando los arreglos son 1D, `np.column_stack()` y `np.hstack()` se comportan diferente

In [16]:
a = np.array([4.,2.])
b = np.array([3.,8.])

In [170]:
np.column_stack((a,b))

array([[4., 3.],
       [2., 8.]])

In [171]:
np.hstack((a,b)) 

array([4., 2., 3., 8.])

- Podemos crear nuevas dimensiones en el arreglo con `np.newaxis` o con `None`

In [18]:
a.shape

(2,)

In [20]:
a[:, np.newaxis].shape

(2, 1)

In [21]:
a[:, None]

array([[4.],
       [2.]])

In [23]:
np.column_stack((a[:, np.newaxis], b[:, np.newaxis]))

array([[4., 3.],
       [2., 8.]])

- Por otro lado, la función `row_stack` es equivalente a `vstack` para cualquier arreglo de entrada. De hecho, `row_stack` es un alias para `vstack`

In [24]:
np.row_stack is np.vstack

True

- En general, para arreglos con más de dos dimensiones:
    
    - `hstack` apila a lo largo del segundo eje, 
    
    - `vstack` apila a lo largo del primer eje y 
    
    - `concatenate` permite argumentos opcionales que dan el número del eje (`axis`) a lo largo del cual debe ocurrir la concatenación.

In [25]:
a

array([4., 2.])

In [26]:
b

array([3., 8.])

In [30]:
b[:, None]

array([[3.],
       [8.]])

In [34]:
np.concatenate((a[:, None, None],b[:, None, None]), axis=2)

array([[[4., 3.]],

       [[2., 8.]]])

***
## Separar un arreglo en varios más pequeños

In [35]:
a = np.floor(10*np.random.random((2,12)))
a

array([[5., 2., 7., 1., 8., 9., 9., 8., 7., 7., 3., 0.],
       [7., 3., 7., 6., 9., 8., 1., 2., 0., 3., 8., 7.]])

In [36]:
np.hsplit(a,3)   # Split a into 3

[array([[5., 2., 7., 1.],
        [7., 3., 7., 6.]]), array([[8., 9., 9., 8.],
        [9., 8., 1., 2.]]), array([[7., 7., 3., 0.],
        [0., 3., 8., 7.]])]

In [181]:
np.hsplit(a, (3,4))   # Split a after the third and the fourth column

[array([[4., 5., 5.],
        [9., 9., 8.]]), array([[4.],
        [8.]]), array([[8., 8., 8., 5., 7., 9., 5., 5.],
        [5., 5., 1., 6., 1., 2., 3., 8.]])]

In [182]:
help(np.hsplit)

Help on function hsplit in module numpy:

hsplit(ary, indices_or_sections)
    Split an array into multiple sub-arrays horizontally (column-wise).
    
    Please refer to the `split` documentation.  `hsplit` is equivalent
    to `split` with ``axis=1``, the array is always split along the second
    axis regardless of the array dimension.
    
    See Also
    --------
    split : Split an array into multiple sub-arrays of equal size.
    
    Examples
    --------
    >>> x = np.arange(16.0).reshape(4, 4)
    >>> x
    array([[  0.,   1.,   2.,   3.],
           [  4.,   5.,   6.,   7.],
           [  8.,   9.,  10.,  11.],
           [ 12.,  13.,  14.,  15.]])
    >>> np.hsplit(x, 2)
    [array([[  0.,   1.],
           [  4.,   5.],
           [  8.,   9.],
           [ 12.,  13.]]),
     array([[  2.,   3.],
           [  6.,   7.],
           [ 10.,  11.],
           [ 14.,  15.]])]
    >>> np.hsplit(x, np.array([3, 6]))
    [array([[  0.,   1.,   2.],
           [  4.,   5.,   6

***
## Mutabilidad y clonado

Al operar y manipular arreglos, los datos a veces se copian en un nuevo arreglo y otras no. Esto es a menudo una fuente de confusión para los principiantes. Hay tres casos:

In [37]:
a = np.arange( 12 )
b = a
b is a

True

In [38]:
b.shape = 3, 4
a.shape

(3, 4)

- Cortar una matriz devuelve una vista de ella:

In [39]:
a

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [40]:
s = a [:, 1:3]
s

array([[ 1,  2],
       [ 5,  6],
       [ 9, 10]])

In [41]:
s is a

False

#### Copia profunda 

El método de copy hace una copia completa de la matriz y sus datos.

In [44]:
# a new array object with new data is created
d = a.copy()
d[0,0]=10
d

array([[10,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [45]:
a

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [194]:
d is a

False

In [195]:
d == a

array([[ True,  True,  True,  True],
       [ True,  True,  True,  True],
       [ True,  True,  True,  True]])

***
# Rutinas de NumPy

[Rutinas y funcionalidad](https://numpy.org/devdocs/reference/routines.html#routines)

***
# Para usuarios ***pro*** (como ustedes)

## *Broadcasting* (difusión)

- Este mecanismo permite que las funciones universales manejen de manera significativa entradas que no tienen exactamente la misma forma.

[General Broadcasting Rules](https://numpy.org/devdocs/user/basics.broadcasting.html)

- Un ejemplo:

In [46]:
x = np.arange(4)
x

array([0, 1, 2, 3])

In [211]:
xx = x.reshape(4,1)
xx

array([[0],
       [1],
       [2],
       [3]])

In [224]:
x + xx

array([[0, 1, 2, 3],
       [1, 2, 3, 4],
       [2, 3, 4, 5],
       [3, 4, 5, 6]])

In [212]:
x.shape

(4,)

In [213]:
xx.shape

(4, 1)

- El *broadcasting* proporciona una forma conveniente de tomar el producto externo (o cualquier otra operación externa) de dos matrices. El siguiente ejemplo muestra una operación de adición externa de dos matrices 1D:

In [48]:
a = np.array([0.0, 10.0, 20.0, 30.0])
b = np.array([1.0, 2.0, 3.0])

In [50]:
a[:, None].shape

(4, 1)

In [53]:
b[None, :].shape

(1, 3)

In [54]:
b[None, :]

array([[1., 2., 3.]])

In [55]:
b

array([1., 2., 3.])

In [222]:
a[:, None] + b

array([[ 1.,  2.,  3.],
       [11., 12., 13.],
       [21., 22., 23.],
       [31., 32., 33.]])

Aquí, `None` inserta un nuevo eje en `a`, haciéndolo un arreglo bidimensional de `4x1`. Al combinar este arreglo de `4x1` con `b`, que tiene forma `(3,)`, resulta un arreglo de `4x3`

### ¿Por qué funciona?

- Cuando se operan dos arreglos, NumPy compara sus formas (`shape`) elemento a elemento, empezando por la última dimensión y hacia arriba. 

- Dos dimensiones son compatibles cuando:
    
    - Son iguales, o
    
    - Una de ellas es 1
    
- Cuando alguna de las dos dimensiones es uno, **se utiliza la otra**. 

    - En otras palabras, las dimensiones con tamaño 1 son "estiradas" o "copiadas" para ajustarse a la otra.

***
## *Fancy indexing* y trucos de indexación

- NumPy ofrece más funciones de indexación que las secuencias regulares de Python. Además de la indexación por enteros y sectores, como vimos antes, las matrices se pueden indexar por matrices de enteros y matrices de booleanos.

In [56]:
a = np.arange(11)**2
a

array([  0,   1,   4,   9,  16,  25,  36,  49,  64,  81, 100], dtype=int32)

In [227]:
i = np.array( [ 1,1,3,8,5 ] )
i

array([1, 1, 3, 8, 5])

In [57]:
a[[ 1,1,3,8,5 ]]

array([ 1,  1,  9, 64, 25], dtype=int32)

In [228]:
a[i]   # the elements of a at the positions i

array([ 1,  1,  9, 64, 25], dtype=int32)

In [58]:
j = np.array([[ 3, 4], [ 9, 7 ]])  # a bidimensional array of indices
j

array([[3, 4],
       [9, 7]])

In [233]:
a[j] # the same shape as j

array([[ 9, 16],
       [81, 49]], dtype=int32)

- También podemos dar índices para más de una dimensión. Las matrices de índices para cada dimensión deben tener la misma forma.

In [235]:
a = np.arange(12).reshape(3,4)
a

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [236]:
i = np.array([[0,1], [1,2]])
j = np.array([[2,1], [3,3]])

In [238]:
i

array([[0, 1],
       [1, 2]])

In [239]:
j

array([[2, 1],
       [3, 3]])

In [240]:
a[i,j] # i and j must have equal shape

array([[ 2,  5],
       [ 7, 11]])

In [241]:
a[i,2]

array([[ 2,  6],
       [ 6, 10]])

In [242]:
a[:,j]

array([[[ 2,  1],
        [ 3,  3]],

       [[ 6,  5],
        [ 7,  7]],

       [[10,  9],
        [11, 11]]])

***
### Búsqueda del máximo

In [244]:
data = np.sin(np.arange(20)).reshape(5,4)
data

array([[ 0.        ,  0.84147098,  0.90929743,  0.14112001],
       [-0.7568025 , -0.95892427, -0.2794155 ,  0.6569866 ],
       [ 0.98935825,  0.41211849, -0.54402111, -0.99999021],
       [-0.53657292,  0.42016704,  0.99060736,  0.65028784],
       [-0.28790332, -0.96139749, -0.75098725,  0.14987721]])

In [247]:
# index of the maxima for each series
ind = data.argmax(axis=0)
ind

array([2, 0, 3, 1], dtype=int64)

***
###  Asignación múltiple con indexación

In [248]:
a = np.arange(5)
a

array([0, 1, 2, 3, 4])

In [250]:
a[[1,3,4]] = 0
a

array([0, 0, 2, 0, 0])

In [253]:
# Se queda la última asignación
a = np.arange(5)
a[[0,0,2]] = [1,2,3]
a

array([2, 1, 3, 3, 4])

***
### Indexado con arreglos booleanos

- Cuando indexamos arreglos con otros arreglos de índices (enteros), proporcionamos la lista de índices para elegir. Con los índices booleanos, el enfoque es diferente; **elegimos explícitamente qué elementos de la matriz queremos y cuáles no**.

La forma más natural en la que uno puede pensar para la indexación booleana es usar matrices booleanas que tengan la misma forma que la matriz original:

In [64]:
a = np.arange(12).reshape(3,4)
a

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [65]:
b = a > 4
b

array([[False, False, False, False],
       [False,  True,  True,  True],
       [ True,  True,  True,  True]])

In [67]:
a[a>5]

array([ 6,  7,  8,  9, 10, 11])

- También se puede utilizar en asignaciones:

In [68]:
a[a>5] = 0
a

array([[0, 1, 2, 3],
       [4, 5, 0, 0],
       [0, 0, 0, 0]])

***
# Álgebra lineal

In [261]:
a = np.array([[1.0, 2.0], [3.0, 4.0]])
a

array([[1., 2.],
       [3., 4.]])

In [262]:
a.transpose()

array([[1., 3.],
       [2., 4.]])

In [263]:
np.linalg.inv(a)

array([[-2. ,  1. ],
       [ 1.5, -0.5]])

In [264]:
np.eye(2)

array([[1., 0.],
       [0., 1.]])

In [265]:
j = np.array([[0.0, -1.0], [1.0, 0.0]])

j @ j

array([[-1.,  0.],
       [ 0., -1.]])

In [267]:
y = np.array([[5.], [7.]])
y

array([[5.],
       [7.]])

In [268]:
np.linalg.solve(a, y)

array([[-3.],
       [ 4.]])

In [273]:
# eigenvalores y eigenvectores
np.linalg.eig(a)

(array([-0.37228132,  5.37228132]), array([[-0.82456484, -0.41597356],
        [ 0.56576746, -0.90937671]]))

***
# *Tarea*

1. De las siguientes secciones, escoger 73 funciones de NumPy y mostrar su utilización en un ejemplo.

    - [Array creation routines](https://numpy.org/devdocs/reference/routines.array-creation.html)

    - [Array manipulation routines](https://numpy.org/devdocs/reference/routines.array-manipulation.html)

    - [Binary operations](https://numpy.org/devdocs/reference/routines.bitwise.html)

    - [String operations](https://numpy.org/devdocs/reference/routines.char.html)
    

2. Crear un ejemplo de cómo guardar y cargar arreglos de un archivo binario `.npy` y `.npz`:

    - [NumPy binary files (NPY, NPZ)](https://numpy.org/devdocs/reference/routines.io.html#numpy-binary-files-npy-npz)
    
3. Crear un ejemplo de cómo guardar y cargar arreglos de un archivo de texto `.txt`:

    - [NumPy Text files](https://numpy.org/devdocs/reference/routines.io.html#text-files)    
    
4. Crear una función llamada `estimacionMCO` que lea un archivo CSV con 7 columnas, que corresponden a las variables $(x_{1i}, \ldots, x_{6i})$ y $y_i$. 
    - La función debe computar matricialmente los parámetros del modelo de regresión lineal: $y = X\beta$. 
    - Estos parámetros deben ser devueltos como un arreglo de NumPy. 

    - Utilice la función de lectura de archivos de NumPy.